classifier:
    seamr.learn.ace.ACE:
        cutlevel: 0.000001
        acceptor:
            sklearn.linear_model.LogisticRegression:
                solver: "lbfgs"
                penalty: "l2"
                
        expert:    
            sklearn.ensemble.RandomForestClassifier:
                criterion: gini
                max_leaf_nodes: 32
                n_estimators: 64
                max_features: log2

        generalist:
            sklearn.tree.DecisionTreeClassifier:
                criterion: gini
                max_features: null
                max_leaf_nodes: 1024
