classifier:
    seamr.learn.BoostedClassifier:
        key: "bagged-svm"
        n_estimators: 32
        max_samples: 3000
        n_jobs: 16
        estimator:
            sklearn.svm.SVC:
                probability: true
