classifier:
    seamr.learn.BoostedClassifier:
        key: "bagged-nb"
        n_estimators: 32
        max_samples: 1000
        n_jobs: -1
        estimator:
            sklearn.naive_bayes.GaussianNB:
                priors: null
