classifier:
    seamr.learn.sense.SensibleClassifier:
        semthreshold: 0.1
        estimator:
            sklearn.ensemble.RandomForestClassifier:
                criterion: gini
                n_jobs: -1
                min_samples_leaf: 50
                max_leaf_nodes: 2048
                n_estimators: 32
                max_features: null
