classifier:
    seamr.learn.smoothing.SmoothEstimator:
        classifier: 
            sklearn.ensemble.RandomForestClassifier:
                criterion: gini
                n_jobs: -1
                max_leaf_nodes: 2048
                n_estimators: 32
                max_features: null
