classifier:
    seamr.learn.BoostedClassifier:
        key: "bagged-svm"
        booster:
            sklearn.ensemble.BaggingClassifier:
                base_estimator: null
                n_estimators: 128
                max_samples: 500
                n_jobs: -1
        estimator:
            sklearn.svm.SVC:
                probability: true
